type Query {
  userTest: String @upperCase
  userFindOne(user: UserInput!): UserOutput
  userFindMany(user: UserInput): [UserOutput]
  userFindById(_id: ID!): UserOutput
  userFindManyById(_ids: [ID]!): [UserOutput]
}

type Mutation {
  userTest(test: Email!): String!
  userCreate(user: UserInput!): UserOutput
  userUpdateById(_id: ID, user: UserInput!): UserOutput
  userRemoveById(_id: ID): Boolean!
}

type UserOutput {
  _id: ID
  createdAt: String
  updateAt: String
  firstName: String
  lastName: String
  email: String
}

input UserInput {
  firstName: String
  lastName: String
  email: String
  password: String
}

type User {
  _id: ID
  createdAt: String
  updateAt: String
  firstName: String
  lastName: String
  email: String
  password: String
}
